Update dependencies
The newer slint failed to build:

    Package fontconfig was not found in the pkg-config search path

Setting `RUST_FONTCONFIG_DLOPEN` as suggested in a [bug report] leads to
a different build error:

    unresolved imports `fontconfig_sys::FcCharSetAddChar`, `fontconfig_sys::FcCharSetCopy`, `fontconfig_sys::FcCharSetCreate`, ...

Install fontconfig for the build to succeed. Update first to prevent
404s from packages no longer existing on mirrors.

[bug report]: https://github.com/slint-ui/slint/issues/2376